"""update  clients table

Revision ID: cacdb506cd39
Revises: eda5e4045824
Create Date: 2026-01-05 17:09:57.073298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cacdb506cd39'
down_revision: Union[str, Sequence[str], None] = 'eda5e4045824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'handoff_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('handoff_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
