"""create clients table

Revision ID: eda5e4045824
Revises: 
Create Date: 2026-01-05 14:19:59.207375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda5e4045824'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    #sa.Column('enable_agent_handoff', sa.Boolean(), nullable=True),
    sa.Column(
    'enable_agent_handoff',
    sa.Boolean(),
    server_default=sa.text("false"),
    nullable=False
),
    sa.Column('handoff_message', sa.String(), nullable=True),
    sa.Column('memory_enabled', sa.Boolean(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    #sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column(
    'created_at',
    sa.DateTime(),
    server_default=sa.text("now()"),
    nullable=False
),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
